import json,hashlib,pathlib,collections,subprocess,sys
R=pathlib.Path(__file__).resolve().parents[2];A=R/"artifacts"/"lane-c";O=A/"C1_HISTORY_DERIVATIVE_VALIDATION_V2.json"
TP="artifacts/lane-c/C1_HISTORY_BEHAVIOR_TRAIN_V1.jsonl";PP="artifacts/lane-c/C1_HISTORY_BEHAVIOR_REPLAY_V1.jsonl"
G=lambda p:subprocess.check_output(["git","show","HEAD:"+p],cwd=R);L=lambda b:[json.loads(x) for x in b.decode("utf-8").splitlines() if x.strip()]
tb,pb=G(TP),G(PP);t,p=L(tb),L(pb);H=lambda b:hashlib.sha256(b).hexdigest()
tc=dict(sorted(collections.Counter(x["source_behavior"] for x in t).items()));pc=dict(sorted(collections.Counter(x["source_behavior"] for x in p).items()))
ET={"C1-BA-001":2,"C1-BA-002":2,"C1-BA-003":2,"C1-BA-004":2,"C1-BA-006":2,"C1-BA-007":2,"C1-BA-008":2};EP={f"C1-BA-{i:03d}":1 for i in range(1,9)}
tk={"row_id","source_behavior","split","prompt","preferred","rejected","privacy"};pk={"row_id","source_behavior","split","criterion"}
b=[x for x in p if x["source_behavior"]=="C1-BA-005"];ti={x["row_id"] for x in t};pi={x["row_id"] for x in p}
c={"train_sha":H(tb)=="0fbd18f7e999fbc92ef10167fde6b1f8af35a544f5c955a3cbceebbdf9deed12","replay_sha":H(pb)=="f97ce0322804efed56ed50e4372d29aae0ae6de080f282ce2985fa2272c3f477","rows":len(t)==14 and len(p)==8,"schemas":all(set(x)==tk for x in t) and all(set(x)==pk for x in p),"splits":all(x["split"]=="train" for x in t) and all(x["split"] in {"replay","external_only"} for x in p),"privacy":all(x["privacy"]=="SYNTHETIC_PUBLIC_SAFE" for x in t),"counts":tc==ET and pc==EP,"ba005":not any(x["source_behavior"]=="C1-BA-005" for x in t) and len(b)==1 and b[0]["split"]=="external_only","ids_disjoint":not(ti&pi)}
s="PASS" if all(c.values()) else "FAIL";r={"schema":"C1_HISTORY_DERIVATIVE_VALIDATION_V2","supersedes":"C1_HISTORY_DERIVATIVE_VALIDATION_V1","status":s,"input_mode":"GIT_BLOB_BYTES_AT_HEAD","source_head":subprocess.check_output(["git","rev-parse","HEAD"],cwd=R,text=True).strip(),"inputs":{"train_sha256":H(tb),"replay_sha256":H(pb)},"counts":{"train_rows":len(t),"replay_rows":len(p),"train_per_behavior":tc,"replay_per_behavior":pc},"checks":c,"governance":{"protected_eval_consumed":False,"shared_gpu_used":False,"weight_change":False,"derivative_source_blobs_changed":False,"ba005_neural_training":False},"known_v1_defect":"V1 referenced nonexistent behavior/external_only fields.","known_v2_precheck_defect":"Filesystem checkout hashing is EOL-sensitive on Windows; authoritative validation uses Git blob bytes at HEAD."}
O.write_text(json.dumps(r,indent=2)+"\n",encoding="utf-8");print(json.dumps(r,sort_keys=True));sys.exit(0 if s=="PASS" else 41)
